controller_list:
  - name: fake_kuka_lwr_right_controller
    joints:
      - kuka_lwr_right_0_joint
      - kuka_lwr_right_1_joint
      - kuka_lwr_right_2_joint
      - kuka_lwr_right_3_joint
      - kuka_lwr_right_4_joint
      - kuka_lwr_right_5_joint
      - kuka_lwr_right_6_joint
  - name: fake_kuka_lwr_left_controller
    joints:
      - kuka_lwr_left_0_joint
      - kuka_lwr_left_1_joint
      - kuka_lwr_left_2_joint
      - kuka_lwr_left_3_joint
      - kuka_lwr_left_4_joint
      - kuka_lwr_left_5_joint
      - kuka_lwr_left_6_joint