lbh:
  lbh_j11_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j11_joint
  lbh_j12_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j12_joint
  lbh_j22_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j22_joint
  lbh_j32_position_controller:
    type: position_controllers/JointPositionController
    joint: lbh_j32_joint
