rbh:
  rbh_j11_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j11_joint
  rbh_j12_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j12_joint
  rbh_j22_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j22_joint
  rbh_j32_position_controller:
    type: position_controllers/JointPositionController
    joint: rbh_j32_joint
